# Example of app.yaml
# Used in Google App Engine applications

runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /.*
  script: main.app
  secure: always


libraries:

- name: numpy
  version: "1.6.1"

- name: ssl
  version: latest


skip_files:

  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\.(?!env).*$
  - ^(.*/)?_ide_helper\.php$
  - ^(.*/)?\.DS_Store$
